require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SharedResourcesController do

  # This should return the minimal set of attributes required to create a valid
  # SharedResource. As you add validations to SharedResource, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "path" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SharedResourcesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all shared_resources as @shared_resources" do
      shared_resource = SharedResource.create! valid_attributes
      get :index, {}, valid_session
      assigns(:shared_resources).should eq([shared_resource])
    end
  end

  describe "GET show" do
    it "assigns the requested shared_resource as @shared_resource" do
      shared_resource = SharedResource.create! valid_attributes
      get :show, {:id => shared_resource.to_param}, valid_session
      assigns(:shared_resource).should eq(shared_resource)
    end
  end

  describe "GET new" do
    it "assigns a new shared_resource as @shared_resource" do
      get :new, {}, valid_session
      assigns(:shared_resource).should be_a_new(SharedResource)
    end
  end

  describe "GET edit" do
    it "assigns the requested shared_resource as @shared_resource" do
      shared_resource = SharedResource.create! valid_attributes
      get :edit, {:id => shared_resource.to_param}, valid_session
      assigns(:shared_resource).should eq(shared_resource)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SharedResource" do
        expect {
          post :create, {:shared_resource => valid_attributes}, valid_session
        }.to change(SharedResource, :count).by(1)
      end

      it "assigns a newly created shared_resource as @shared_resource" do
        post :create, {:shared_resource => valid_attributes}, valid_session
        assigns(:shared_resource).should be_a(SharedResource)
        assigns(:shared_resource).should be_persisted
      end

      it "redirects to the created shared_resource" do
        post :create, {:shared_resource => valid_attributes}, valid_session
        response.should redirect_to(SharedResource.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved shared_resource as @shared_resource" do
        # Trigger the behavior that occurs when invalid params are submitted
        SharedResource.any_instance.stub(:save).and_return(false)
        post :create, {:shared_resource => { "path" => "invalid value" }}, valid_session
        assigns(:shared_resource).should be_a_new(SharedResource)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SharedResource.any_instance.stub(:save).and_return(false)
        post :create, {:shared_resource => { "path" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested shared_resource" do
        shared_resource = SharedResource.create! valid_attributes
        # Assuming there are no other shared_resources in the database, this
        # specifies that the SharedResource created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SharedResource.any_instance.should_receive(:update).with({ "path" => "MyString" })
        put :update, {:id => shared_resource.to_param, :shared_resource => { "path" => "MyString" }}, valid_session
      end

      it "assigns the requested shared_resource as @shared_resource" do
        shared_resource = SharedResource.create! valid_attributes
        put :update, {:id => shared_resource.to_param, :shared_resource => valid_attributes}, valid_session
        assigns(:shared_resource).should eq(shared_resource)
      end

      it "redirects to the shared_resource" do
        shared_resource = SharedResource.create! valid_attributes
        put :update, {:id => shared_resource.to_param, :shared_resource => valid_attributes}, valid_session
        response.should redirect_to(shared_resource)
      end
    end

    describe "with invalid params" do
      it "assigns the shared_resource as @shared_resource" do
        shared_resource = SharedResource.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SharedResource.any_instance.stub(:save).and_return(false)
        put :update, {:id => shared_resource.to_param, :shared_resource => { "path" => "invalid value" }}, valid_session
        assigns(:shared_resource).should eq(shared_resource)
      end

      it "re-renders the 'edit' template" do
        shared_resource = SharedResource.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SharedResource.any_instance.stub(:save).and_return(false)
        put :update, {:id => shared_resource.to_param, :shared_resource => { "path" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested shared_resource" do
      shared_resource = SharedResource.create! valid_attributes
      expect {
        delete :destroy, {:id => shared_resource.to_param}, valid_session
      }.to change(SharedResource, :count).by(-1)
    end

    it "redirects to the shared_resources list" do
      shared_resource = SharedResource.create! valid_attributes
      delete :destroy, {:id => shared_resource.to_param}, valid_session
      response.should redirect_to(shared_resources_url)
    end
  end

end
